### ISSUE TITLE
Use the tutorial

### ISSUE THREAD

**Issue by yangyang-studio** [jamesstill/Astronomy#16]
Hello, sir.

Can you get a video tutorial? I don't know how to use it at present. I used VS2022. This library was successfully installed, but I don't know how to use it.

thank you

**Comment by jamesstill** [comment]
Astronomical calculations are very difficult! I recommend studying the [unit tests](https://github.com/jamesstill/Astronomy/tree/main/test/SquareWidget.Astronomy.Core.Tests). Also in the [src folder](https://github.com/jamesstill/Astronomy/tree/main/src) are five tutorials (numbered 1 through 5) that should get you started. Good luck!
